### ISSUE TITLE
Community blog on Medium

### ISSUE THREAD

**Issue by pavsaund** [VestfoldDevelopers/Community#15]
## Sales pitch
Starting to blog is hard. First you need to take the step to establish a blog. Then decide what to write. Then actually start writing. Then you need to keep it consistent. During all of this you probably need to adjust your theme. Reach out and spread your content. Build up your following. *This is hard.*

What if VD could host a community blog where we have taken away most of these decisions from you? An established blog, with a fixed theme, with existing content and following. A place where you can write a post on whatever topic you like (within VD's community rules, and targeted towards our audience). A place where you can receive formal feedback and help to improve your posts before it's published.

If you're already a blogger, then spreading your existing and new content to a blog like this will potentially expose you to a new audience and drive traffic back to your own blog.

The idea is heavily inspired by [Free code camp](https://medium.freecodecamp.com).

## Suggestion
**Bloghosting:** Medium
**Langauge**: ~~Norwegian~~
Based on discussion below, the main language of the site can be English, but we support posts in both English and Norwegian.

**Target audience**:
 - Developers looking to learn new skills.
 - Intro topics in many fields of SW development. 

**Post style:**
 - How-to's.
 - Intro's. 
 - Experiences

**What we don't want:**
 - Low-level technical posts that hit a very narrow audience. 
 - Rants ~~that don't give any value~~.
 - Random off-topic posts.

**Who decides? How do we decide?**
 - Someone needs to own and guide which posts can and can't go out.
 - As with other aspects of VD, there should be full transparency to decisions and decision process'
 - We can have a separate label on GH for blog related stuff

**Comment by reminyborg** [comment]
I am sold on the sales pich! 😃

We are a norwegian comunity and i see the reasonings behind having the blog in :norway:. I want do disscuss the pro's and con's of this.

*pro's:*

- easier bar of entry (is this true?)
- :norway: dev-blogs are rare

*con's*

- Much smaller market 🌍

**Comment by g2petter** [comment]
**Con**
Not all Norwegian developers have Norwegian as their first language. Could possibly make the argument that they are more important to reach, as they're likely to have a smaller local network.

**Comment by pavsaund** [comment]
I totally see your point, and I've been through those thoughts myself. I'd like to add a few points though. 
To explain my motivation: To allow inexperienced devs a place to both blog, and reap benefits from that blog through visibility in the local community.

*Assumptions (from me)*
 - Better impact with local reach => can lead to more job possibilities, career focus.
 - Chance to appeal to a different audience, **because** 🇳🇴-blogs are rare.
 - English blogs tend to disappear in the vast internet, but in Norwegian the post actually may stand out.

Here's a few Norwegian blogs, I know of, that stand out: 
 - http://open.bekk.no
 - http://blog.kjempekjekt.com

--- 

Looking at it from another angle: We can be part of preparing inexperienced devs to blogging in english. And the potential reach of english is both the local & international community.

**Comment by pavsaund** [comment]
A follow-up question:
If we blog in English, should we then limit the blog to be only for Vestfold?

**Comment by anemaecore** [comment]
No limits. Let us just create a philosophy, and see where it takes us.

**Comment by reminyborg** [comment]
@pavsaund An answer to the follow-up question:
Having the blog in Norwegian creates a stronger connection to Vestfold, and grounds it.
I have a feeling that having the blog in English would open up a pandoras box.

**Comment by anemaecore** [comment]
Pandora <3

**Comment by reminyborg** [comment]
If we keep the blog in Norwegian it also makes sense to announce local events and meetups between blogposts. (Example http://open.bekk.no

**Comment by pavsaund** [comment]
@anemacore: So would you propose an open attitude towards language? Blog in the language that suits and see where that takes us?

@reminyborg / @g2petter: Perhaps keeping the identity of VD will allow us to blog in English, but at the same time have a local focus.

**Comment by tpresthus** [comment]
Would another possibility be to allow both Norwegian and English posts, and tag/categorize them by language?

I definitely see the point of anchoring the blog to Vestfold, but I think @g2petter makes a very valid point regarding non-norwegian developers in the area.

**Comment by reminyborg** [comment]
@pavsaund @tpresthus @anemaecore  agreed!

**Comment by pavsaund** [comment]
So, the blog's main outward-facing language should be English. Menu-items, about pages etc. But content can be both English and Norwegian.

**Comment by pavsaund** [comment]
Updated issue

**Comment by pavsaund** [comment]
Medium publication available here: https://medium.com/vestfolddevelopers/

I've requested the domain http://medium.vestfolddevelopers.no.

**Comment by pavsaund** [comment]
The url is now working! http://medium.vestfolddevelopers.no/

**Comment by pavsaund** [comment]
Now the blog has been activated, I've asked @reminyborg to help out as an editor and to help produce content. The idea is that this is a community blog, but we still need editors to ensure a certain level of quality, and to suggest topics that anyone can write.

We're going to try an initial stab at writing with an open process in mind: https://github.com/VestfoldDevelopers/Community/projects/2. 

We'll add guidelines for blog posts soon, but for now if you're interested in writing/submitting a post, please submit an issue, and we'll assign a blog-label to it, and move it along the pipeline. 

Reblogging is accepted, as long as you are the original author, and it suits our publication.

Happy writing!
