### ISSUE TITLE
Agenda / Topics

### ISSUE THREAD

**Issue by pavsaund** [VestfoldDevelopers/Community#6]
This is a proposal for the agenda of the evenings talks. There are 4 slots allocated for talks. 1 for each community group and a wildcard.

TODO:
- [x] Decide on Agenda structure (talk length / break length)
- [x] Decide on Session 1
- [x] Decide on Session 2
- [ ] Decide on Session 3

## 10 minute breaks - 3 sessions

[17:30-17:35] Intro
[17:35-18:10] Session 1 - Vestfold Whitehats
[18:10-18:50] Break w/ refreshments
[18:50-19:35] Session 2 - NNUG
[19:45-20:30] Session 3 - JavaBin
[20:30-20:32] Closing

## Early Proposals 
These were the initial proposals

### ~~10 minute breaks~~
- [17:25-17:30] Intro
- [17:30-18:00] Session 1 - Vestfold Whitehats
- [18:10-18:40] Session 2 - NNUG 
- [18:40-19:10] Break w/ refreshments
- [19:10-19:40] Session 3 - JavaBin
- [19:50-20:20] Session 4 - Open / WildCard / CFP
- [20:20-20:25] Closing

### ~~5 minute breaks~~
- [17:25-17:30] Intro
- [17:30-18:00] Session 1 - Vestfold Whitehats
- [18:05-18:35] Session 2 - NNUG 
- [18:35-19:15] Break w/ refreshments
- [19:15-19:45] Session 3 - JavaBin
- [19:50-20:20] Session 4 - Open / WildCard / CFP
- [20:20-20:25] Closing

**Comment by anemaecore** [comment]
Session 1 - Vestfold Whitehats

Topic: Sikker kommunikasjon med Crypho

Yiorgis Gozadinos og Geir Bækholt kommer for å fortelle oss litt hvordan de forholder seg til sikkerhet - en oppskrift som har ført dem helt til topps i internasjonal sikkerhet.

De har utviklet Crypho - en prisvinnende applikasjon for sikker overføring av sensitive data.

Ende-til-ende-kryptering ivaretar sikkerheten, både mot overvåkning og når det gjelder å overholde norsk lovverk for overføring av sensitive person- og helsedata.

Crypho er i dag i bruk av tusenvis av brukere over hele verden. Det brukes av internasjonale politistyrker, finans institusjoner offentlige etater og mediebedrifter. Crypho beskytter også kommunikasjonen til menneskerettighetsforkjempere i midt-østen, nordafrika og mellomamerika.

Mediene om Crypho: 
http://www.vestviken24.no/vv24naringsliv/ukjente-i-norge-hoster-internasjonal-oppmerksomhet/s/5-83-4391 
http://www.tu.no/artikler/norske-krypto-selskaper-gjor-det-skarpt-etter-snowden-avsloringene/232135 


Crypho vant Dataforeningens prestisjefylte IT-sikkerhetspris - Rosing prisen.
https://www.crypho.no/rosing.html

Blog:
http://blog.crypho.com/post/132010752814/ipacso

**Comment by pavsaund** [comment]
Proposing to keep fewer sessions, and longer sessions. Thoughts?

---

## 10 minute breaks - 3 sessions

[17:30-17:35] Intro
[17:35-18:10] Session 1 - Vestfold Whitehats
[18:20-19:05] Session 2 - NNUG
[19:05-19:45] Break w/ refreshments
[19:45-20:30] Session 3 - JavaBin
[20:30-20:32] Closing

**Comment by pavsaund** [comment]
Moving the long break ahead by one slot so that we can more easily match the opening hours of the canteen.

## Also, going for this last option, unless something comes up

## 10 minute breaks - 3 sessions

[17:30-17:35] Intro
[17:35-18:10] Session 1 - Vestfold Whitehats
[18:10-18:50] Break w/ refreshments
[18:50-19:35] Session 2 - NNUG
[19:45-20:30] Session 3 - JavaBin
[20:30-20:32] Closing

**Comment by pavsaund** [comment]
Session 2 - NNUG Vestfold:

Topic: .NET Core, en enklere API-stack for en frontend utvikler?

Gjermund Bjaanes kommer til oss for å prate om hvorvidt .NET kan være aktuell som en plattform å bruke for en frontendutvikler.

Bio: Gjermund Bjaanes is a developer, geek and enthusiast in general. He's passionate about programming and software engineering. Currently focusing on web and mobile development in his spare time.

Gjermund works for Flatirons Norge (of Flatirons Solutions Inc.) as a Software Engineer. Working mostly with Java and related web technologies (Javascript, Angular, etc). He finds it thrilling to develop software that people use!

Gjermund blogs actively on http://gjermundbjaanes.com.

**Comment by astensby** [comment]
Oppdaget at jeg ikke hadde skrevet noe her!!!

Session 3 - JavaBin Vestfold:

Topic: Intro til Elasticsearch
Aleksander Stensby fra Monokkel AS gir oss en introduksjon til Elasticsearch og mulighetene Elasticsearch gir med tanke på søk, utforskning av data og dataaggregering. Vi får se hvordan man kan navigere strukturert og ustrukturert data gjennom full-tekst søk, samt aggregering og visualisering av data for analyse. Vi skal se på noen utradisjonelle case studies utover tradisjonell full-tekst søk og forhåpentligvis se at Elasticsearch kan hjelpe oss med å lage mye mer enn bare en søkemotor.

**Comment by pavsaund** [comment]
We've got the agenda nailed! :)
